import Icon from '../components/Icon';
import { PageHeader, SectionTitle } from '../components/UI';

const plans=[
  {name:'Gói Khởi đầu',credits:'100',price:'49.000 ₫',desc:'Phù hợp để trải nghiệm và tạo video ngắn.',unit:'490 ₫ / credit'},
  {name:'Gói Nhà sáng tạo',credits:'500',price:'179.000 ₫',desc:'Tối ưu cho nhu cầu sử dụng thường xuyên.',unit:'358 ₫ / credit',featured:true,badge:'TIẾT KIỆM 27%'},
  {name:'Gói Chuyên nghiệp',credits:'1.200',price:'349.000 ₫',desc:'Dành cho dự án cần số lượng video lớn.',unit:'291 ₫ / credit',badge:'GIÁ TỐT NHẤT'},
];
export default function Billing(){return <div className="page-wrap"><PageHeader eyebrow="CREDIT & THANH TOÁN" title="Quản lý credit" description="Theo dõi số dư và mua thêm credit khi bạn cần tạo nhiều video hơn."/>
  <div className="credit-overview"><section className="balance-card"><div className="balance-icon"><Icon name="sparkles" className="w-6 h-6"/></div><div><span>Tổng credit khả dụng</span><strong>120 <small>credit</small></strong><p>Bao gồm credit miễn phí và credit đã mua.</p></div><button className="btn btn-light">Mua thêm credit</button></section><section className="daily-card panel"><div className="daily-head"><div><span>Credit miễn phí hôm nay</span><strong>12 <small>/ 20</small></strong></div><div className="daily-icon"><Icon name="clock" className="w-5 h-5"/></div></div><div className="daily-progress"><i/></div><p>Còn 8 credit • Làm mới lúc 00:00 ngày mai</p></section></div>
  <SectionTitle title="Chọn gói credit" description="Credit đã mua không hết hạn và được cộng ngay sau khi thanh toán."/>
  <div className="plans-grid">{plans.map(p=><article key={p.name} className={`plan-card ${p.featured?'featured':''}`}>{p.badge&&<span className="plan-badge">{p.badge}</span>}<div className="plan-head"><h3>{p.name}</h3><p>{p.desc}</p></div><div className="plan-credit"><strong>{p.credits}</strong><span>credit</span></div><div className="plan-price"><strong>{p.price}</strong><span>{p.unit}</span></div><ul><li><Icon name="check" className="w-4 h-4"/>Credit không hết hạn</li><li><Icon name="check" className="w-4 h-4"/>Dùng cho mọi mô hình AI hỗ trợ</li><li><Icon name="check" className="w-4 h-4"/>Cộng vào tài khoản ngay sau thanh toán</li></ul><button className={`btn full ${p.featured?'btn-primary':'btn-secondary'}`}>Chọn gói này</button></article>)}</div>
  <section className="panel payment-section"><SectionTitle title="Phương thức thanh toán" description="Các phương thức dưới đây là giao diện minh họa cho hệ thống."/><div className="payment-methods"><div className="payment-item selected"><div className="radio"><i/></div><div className="pay-logo bank">BANK</div><div><strong>Chuyển khoản ngân hàng</strong><span>Thanh toán qua mã QR / Internet Banking</span></div></div><div className="payment-item"><div className="radio"/><div className="pay-logo momo">M</div><div><strong>Ví MoMo</strong><span>Thanh toán nhanh qua ứng dụng MoMo</span></div></div><div className="payment-item"><div className="radio"/><div className="pay-logo card"><Icon name="card" className="w-5 h-5"/></div><div><strong>Thẻ ngân hàng</strong><span>Visa, Mastercard, JCB</span></div></div></div></section>
</div>}
