import Icon from '../components/Icon';
import { PageHeader, StatusBadge } from '../components/UI';
const rows=[
 ['VN260810001','Mua gói Nhà sáng tạo','+500','179.000 ₫','Đã thanh toán','10/08/2026 08:31'],
 ['VD260810021','Tạo video: Lái xe đêm Tokyo','-10','—','Đã cộng','10/08/2026 08:42'],
 ['VD260809018','Tạo video: Cyberpunk portrait','-10','—','Đã cộng','09/08/2026 21:16'],
 ['FREE260809','Credit miễn phí hằng ngày','+20','0 ₫','Đã cộng','09/08/2026 00:00'],
 ['VN260805004','Mua gói Khởi đầu','+100','49.000 ₫','Đã thanh toán','05/08/2026 17:22'],
];
export default function Transactions(){return <div className="page-wrap"><PageHeader eyebrow="LỊCH SỬ GIAO DỊCH" title="Biến động credit" description="Theo dõi các lần mua credit, credit miễn phí và chi phí tạo video." action={<button className="btn btn-secondary"><Icon name="download" className="w-4 h-4"/>Xuất lịch sử</button>}/><div className="transaction-summary"><div><span>Credit đã mua</span><strong>600</strong><small>Tổng cộng</small></div><div><span>Credit đã sử dụng</span><strong>480</strong><small>48 tác vụ video</small></div><div><span>Tổng thanh toán</span><strong>228.000 ₫</strong><small>2 giao dịch thành công</small></div></div><div className="table-toolbar"><div className="tabs"><button className="active">Tất cả</button><button>Mua credit</button><button>Sử dụng</button><button>Miễn phí</button></div><div className="search-field"><Icon name="search" className="w-4 h-4"/><span>Tìm mã giao dịch...</span></div></div><section className="table-card"><table><thead><tr><th>Mã giao dịch</th><th>Nội dung</th><th>Credit</th><th>Số tiền</th><th>Trạng thái</th><th>Thời gian</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td><span className={r[2].startsWith('+')?'credit-plus':'credit-minus'}>{r[2]}</span></td><td>{r[3]}</td><td><StatusBadge status={r[4]}/></td><td>{r[5]}</td></tr>)}</tbody></table><div className="table-footer"><span>Hiển thị 5 / 42 giao dịch</span><div className="pagination compact"><button disabled>‹</button><button className="active">1</button><button>2</button><button>3</button><button>›</button></div></div></section></div>}
